# Generated by Django 4.2.3 on 2023-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
