# Generated by Django 4.2.3 on 2023-07-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_contact_contact1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
