# Generated by Django 4.2.3 on 2023-07-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_contact_contact2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
